version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: sigmaChad
      POSTGRES_DB: db
  app:
    image: my-node-app
    ports: 
        - 13000:3001

